# Generated by Django 5.0.1 on 2024-01-23 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='talim',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Qisqacha izoh: '),
        ),
        migrations.AddField(
            model_name='talim',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Qisqacha izoh: '),
        ),
        migrations.AddField(
            model_name='talim',
            name='course_en',
            field=models.CharField(max_length=100, null=True, verbose_name="Yo'nalish nomi: "),
        ),
        migrations.AddField(
            model_name='talim',
            name='course_uz',
            field=models.CharField(max_length=100, null=True, verbose_name="Yo'nalish nomi: "),
        ),
        migrations.AddField(
            model_name='talim',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name="O'qish joyi: "),
        ),
        migrations.AddField(
            model_name='talim',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name="O'qish joyi: "),
        ),
    ]
