# Generated by Django 5.0.1 on 2024-01-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talim', '0002_talim_content_en_talim_content_uz_talim_course_en_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='talim',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Talim'},
        ),
    ]
