# Generated by Django 5.0.1 on 2024-02-03 05:45

import colorfield.fields
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Menu nomi: ')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='Menu nomi: ')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='Menu nomi: ')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Menyular',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tag nomi: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maqola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Loyiha nomi: ')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Loyiha nomi: ')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Loyiha nomi: ')),
                ('description', models.CharField(max_length=500, verbose_name='Qisqa izoh: ')),
                ('description_uz', models.CharField(max_length=500, null=True, verbose_name='Qisqa izoh: ')),
                ('description_en', models.CharField(max_length=500, null=True, verbose_name='Qisqa izoh: ')),
                ('content', tinymce.models.HTMLField(verbose_name="Barcha ma'lumotlar: ")),
                ('content_uz', tinymce.models.HTMLField(null=True, verbose_name="Barcha ma'lumotlar: ")),
                ('content_en', tinymce.models.HTMLField(null=True, verbose_name="Barcha ma'lumotlar: ")),
                ('image', models.ImageField(blank=True, default='assets/pythondjango.jpg', null=True, upload_to='Loyiha/', verbose_name='Maqola rasmi')),
                ('is_active', models.BooleanField(default=False, verbose_name='Nashr etilsinmi? : ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maqola.menu', verbose_name='Menyuni tanlang: ')),
            ],
            options={
                'verbose_name_plural': 'Maqolalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
