# Generated by Django 5.0.1 on 2024-01-23 17:51

import cked.fields
import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tajriba nomi: ')),
                ('center', models.CharField(max_length=100, verbose_name='Ishlagan joyi: ')),
                ('content', cked.fields.RichTextField(verbose_name="Barcha ma'lumotlar: ")),
                ('started_at', models.DateField(verbose_name='Boshlanish vaqti: ')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Tugash vaqti: ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Hozirgi ish joyim: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lohiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Texnologiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Texnologiya nomi: ')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
