# Generated by Django 5.0.1 on 2024-06-21 06:55

import colorfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texnologiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Texnologiya nomi: ')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Loyiha nomi: ')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Loyiha nomi: ')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Loyiha nomi: ')),
                ('description', models.CharField(max_length=500, verbose_name='Qisqa izoh: ')),
                ('description_uz', models.CharField(max_length=500, null=True, verbose_name='Qisqa izoh: ')),
                ('description_en', models.CharField(max_length=500, null=True, verbose_name='Qisqa izoh: ')),
                ('content', tinymce.models.HTMLField(verbose_name="Barcha ma'lumotlar: ")),
                ('content_uz', tinymce.models.HTMLField(null=True, verbose_name="Barcha ma'lumotlar: ")),
                ('content_en', tinymce.models.HTMLField(null=True, verbose_name="Barcha ma'lumotlar: ")),
                ('image', models.ImageField(blank=True, null=True, upload_to='Loyiha/', verbose_name='Post rasmi')),
                ('started_at', models.DateField(verbose_name='Boshlanish vaqti: ')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Tugash vaqti: ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Githubdagi linki: ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Hozirgi ishlab chiqarish jarayonida: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('techno', models.ManyToManyField(to='loyiha.texnologiyalar', verbose_name='Texnologiyalar')),
            ],
            options={
                'verbose_name_plural': 'Lohiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
