# Generated by Django 5.0.1 on 2024-01-23 19:01

import colorfield.fields
import pictures.models
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Texnologiyalar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Texnologiya nomi: ')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Texnologiyalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Loyiha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Loyiha nomi: ')),
                ('content', tinymce.models.HTMLField(verbose_name="Barcha ma'lumotlar: ")),
                ('image', pictures.models.PictureField(aspect_ratios=[None], breakpoints={'l': 1200, 'm': 992, 's': 768, 'xl': 1400, 'xs': 576}, container_width=1200, default='m', file_types=['WEBP'], grid_columns=12, pixel_densities=[1, 2], upload_to='post', verbose_name='Rasm')),
                ('started_at', models.DateField(verbose_name='Boshlanish vaqti: ')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Tugash vaqti: ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Githubdagi linki: ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Hozirgi ishlab chiqarish jarayonida: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('techno', models.ManyToManyField(to='loyiha.texnologiyalar', verbose_name='Texnologiyalar')),
            ],
            options={
                'verbose_name_plural': 'Lohiyalar',
                'ordering': ['-created_at'],
            },
        ),
    ]
