# Generated by Django 5.0.1 on 2024-01-23 18:16

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyiha',
            name='center',
        ),
        migrations.AddField(
            model_name='loyiha',
            name='iframe',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Video embeded: '),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='textwrap',
            field=tinymce.models.HTMLField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Loyiha nomi: '),
        ),
    ]
