# Generated by Django 5.0.1 on 2024-01-23 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyiha',
            name='iframe',
        ),
        migrations.AddField(
            model_name='loyiha',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Githubdagi linki: '),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='techno',
            field=models.ManyToManyField(to='loyiha.texnologiyalar', verbose_name='Ishlatilgan texnologiyalar: '),
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Hozirgi ishlab chiqarish jarayonida: '),
        ),
    ]
