# Generated by Django 5.0.1 on 2024-01-27 04:49

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0002_alter_loyiha_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyiha',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name="Barcha ma'lumotlar: "),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='content_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name="Barcha ma'lumotlar: "),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Loyiha nomi: '),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Loyiha nomi: '),
        ),
    ]
