# Generated by Django 5.0.1 on 2024-01-23 18:32

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0002_remove_loyiha_center_loyiha_iframe_loyiha_textwrap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyiha',
            name='textwrap',
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='content',
            field=tinymce.models.HTMLField(verbose_name="Barcha ma'lumotlar: "),
        ),
    ]
