# Generated by Django 5.0.1 on 2024-01-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loyiha', '0003_loyiha_content_en_loyiha_content_uz_loyiha_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyiha',
            name='description',
            field=models.CharField(default=1, max_length=500, verbose_name='Qisqa izoh: '),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loyiha',
            name='description_en',
            field=models.CharField(max_length=500, null=True, verbose_name='Qisqa izoh: '),
        ),
        migrations.AddField(
            model_name='loyiha',
            name='description_uz',
            field=models.CharField(max_length=500, null=True, verbose_name='Qisqa izoh: '),
        ),
        migrations.AlterField(
            model_name='loyiha',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/Loyiha', verbose_name='Post rasmi'),
        ),
    ]
