# Generated by Django 5.0.1 on 2024-06-21 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tajriba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tajriba nomi: ')),
                ('name_uz', models.CharField(max_length=200, null=True, verbose_name='Tajriba nomi: ')),
                ('name_en', models.CharField(max_length=200, null=True, verbose_name='Tajriba nomi: ')),
                ('center', models.CharField(max_length=100, verbose_name='Ishlagan joyi: ')),
                ('center_uz', models.CharField(max_length=100, null=True, verbose_name='Ishlagan joyi: ')),
                ('center_en', models.CharField(max_length=100, null=True, verbose_name='Ishlagan joyi: ')),
                ('content', models.TextField(verbose_name='Qisqacha izoh: ')),
                ('content_uz', models.TextField(null=True, verbose_name='Qisqacha izoh: ')),
                ('content_en', models.TextField(null=True, verbose_name='Qisqacha izoh: ')),
                ('started_at', models.DateField(verbose_name='Boshlanish vaqti: ')),
                ('ended_at', models.DateField(blank=True, null=True, verbose_name='Tugash vaqti: ')),
                ('is_active', models.BooleanField(default=False, verbose_name='Hozirgi ish joyim: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Tajriba',
                'ordering': ['-created_at'],
            },
        ),
    ]
