# Generated by Django 5.0.1 on 2024-01-23 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tajriba',
            options={'ordering': ['created_at'], 'verbose_name_plural': 'Tajriba'},
        ),
        migrations.AddField(
            model_name='tajriba',
            name='content_en',
            field=models.TextField(null=True, verbose_name='Qisqacha izoh: '),
        ),
        migrations.AddField(
            model_name='tajriba',
            name='content_uz',
            field=models.TextField(null=True, verbose_name='Qisqacha izoh: '),
        ),
        migrations.AddField(
            model_name='tajriba',
            name='name_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Tajriba nomi: '),
        ),
        migrations.AddField(
            model_name='tajriba',
            name='name_uz',
            field=models.CharField(max_length=200, null=True, verbose_name='Tajriba nomi: '),
        ),
        migrations.AddField(
            model_name='tajriba',
            name='position_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozimi: '),
        ),
        migrations.AddField(
            model_name='tajriba',
            name='position_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Lavozimi: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='content',
            field=models.TextField(verbose_name='Qisqacha izoh: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='ended_at',
            field=models.DateField(verbose_name='Tugash vaqti: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Tajriba nomi: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='position',
            field=models.CharField(max_length=100, verbose_name='Lavozimi: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='started_at',
            field=models.DateField(verbose_name='Boshlanish vaqti: '),
        ),
    ]
