# Generated by Django 5.0.1 on 2024-01-23 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0002_alter_tajriba_options_tajriba_content_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tajriba',
            name='ended_at',
            field=models.DateField(blank=True, null=True, verbose_name='Tugash vaqti: '),
        ),
    ]
