# Generated by Django 5.0.1 on 2024-01-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0003_alter_tajriba_ended_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tajriba',
            old_name='position',
            new_name='center',
        ),
        migrations.RenameField(
            model_name='tajriba',
            old_name='position_en',
            new_name='center_en',
        ),
        migrations.RenameField(
            model_name='tajriba',
            old_name='position_uz',
            new_name='center_uz',
        ),
    ]
