# Generated by Django 5.0.1 on 2024-01-23 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0004_rename_position_tajriba_center_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tajriba',
            name='center',
            field=models.CharField(max_length=100, verbose_name='Ishlagan joyi: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='center_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Ishlagan joyi: '),
        ),
        migrations.AlterField(
            model_name='tajriba',
            name='center_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Ishlagan joyi: '),
        ),
    ]
