# Generated by Django 5.0.1 on 2024-01-23 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0005_alter_tajriba_center_alter_tajriba_center_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tajriba',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Hozirgi ish joyim: '),
            preserve_default=False,
        ),
    ]
