# Generated by Django 5.0.1 on 2024-01-23 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0006_tajriba_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tajriba',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Hozirgi ish joyim: '),
        ),
    ]
