# Generated by Django 5.0.1 on 2024-01-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0007_alter_tajriba_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tajriba',
            old_name='active',
            new_name='is_active',
        ),
    ]
