# Generated by Django 5.0.1 on 2024-01-23 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tajriba', '0008_rename_active_tajriba_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tajriba',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Tajriba'},
        ),
    ]
