# Generated by Django 5.0.1 on 2024-02-04 16:41

import colorfield.fields
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aloqa', '0001_initial'),
        ('loyiha', '0005_alter_loyiha_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tarmoq nomi: ')),
                ('icon', models.CharField(max_length=100, verbose_name='Icon kodi: ')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Havola: ')),
                ('color', colorfield.fields.ColorField(default='#007bff', image_field=None, max_length=25, samples=None, verbose_name='Media rangi: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Ijtimoiiy medialar: ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=240, verbose_name='F.I.O: ')),
                ('position', models.CharField(max_length=240, verbose_name='Lavozim: ')),
                ('manzil', models.CharField(max_length=240, verbose_name='Manzil: ')),
                ('email', models.EmailField(max_length=240, verbose_name='Email: ')),
                ('image', models.ImageField(default='assets/me.jpg', upload_to='About/', verbose_name='Bosh sahifa rasmi: ')),
                ('image2', models.ImageField(default='assets/me.jpg', upload_to='About/', verbose_name='Men haqimdagi rasm: ')),
                ('content', tinymce.models.HTMLField(verbose_name="Bosh sahifa ma'lumotlar: ")),
                ('content2', tinymce.models.HTMLField(verbose_name="Barcha ma'lumotlar: ")),
                ('resume', models.FileField(blank=True, null=True, upload_to='resume/', verbose_name='Rezyume: ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('skill', models.ManyToManyField(to='loyiha.texnologiyalar', verbose_name="Ko'nikmalarim: ")),
            ],
            options={
                'verbose_name_plural': 'Rezyume: ',
                'ordering': ['-created_at'],
            },
        ),
    ]
